"""End-to-end checks on the public-domain sample scores in schemas/examples.

The samples are regenerated by tests/make_samples.py; these tests keep the
committed PDFs, the committed gts files and the detector consistent.
"""

import json
import shutil
from fractions import Fraction
from pathlib import Path

import jsonschema
import pytest

from engrave import engrave, find_japanese_font, simulate_scan
from layoutscan import cli
from layoutscan.detect import analyze_page, measure_spans
from layoutscan.render import sha256_of
from make_samples import SAMPLES

REPO = Path(__file__).parents[3]
EXAMPLES = REPO / "schemas" / "examples"
SCHEMA = json.loads((REPO / "schemas" / "gts.schema.json").read_text())


def load(name):
    return json.loads((EXAMPLES / f"{name}.gts.json").read_text())


def measures(document):
    return [m for section in document["sections"] for m in section["measures"]]


def duration(beat):
    d = beat["duration"]
    value = Fraction(1, d["value"]) * (Fraction(3, 2) if d.get("dots") else 1)
    if "tuplet" in d:
        value = value * d["tuplet"][1] / d["tuplet"][0]
    return value


@pytest.mark.parametrize("name", SAMPLES)
def test_If_a_sample_is_loaded_it_should_be_a_valid_gts_filling_every_listed_layer(name):
    document = load(name)

    jsonschema.validate(document, SCHEMA)
    layers = document["meta"]["layers"]
    assert {"layout", "structure", "chords", "tab"} <= set(layers)
    assert all(s.get("label") for s in document["sections"])
    for measure in measures(document):
        assert measure.get("region") and measure.get("chords") and measure.get("beats"), measure["id"]
        assert ("lyrics" in measure) == ("lyrics" in layers), measure["id"]


@pytest.mark.parametrize("name", SAMPLES)
def test_If_a_sample_tab_is_read_every_measure_should_fill_four_four(name):
    for measure in measures(load(name)):
        assert sum(duration(b) for b in measure["beats"]) == 1, measure["id"]


@pytest.mark.parametrize("name", SAMPLES)
def test_If_a_sample_pdf_is_committed_its_hash_should_match_the_gts_source(name):
    assert sha256_of(EXAMPLES / f"{name}.pdf") == load(name)["source"]["sha256"]


def test_If_the_japanese_sample_is_read_verses_should_follow_the_endings():
    sung = [(m.get("volta"), sorted(lyric["verse"] for lyric in m["lyrics"])) for m in measures(load("sakura-sakura"))]

    assert all(verses == [1, 2] for volta, verses in sung if volta is None)
    assert [s for s in sung if s[0]] == [([1], [1]), ([2], [2])]
    assert all(lyric["text"] for m in measures(load("sakura-sakura")) for lyric in m["lyrics"])


@pytest.mark.parametrize("name", SAMPLES)
def test_If_layoutscan_runs_on_a_sample_pdf_it_should_reproduce_the_layout_layer(name, tmp_path):
    pdf = tmp_path / f"{name}.pdf"
    shutil.copy(EXAMPLES / pdf.name, pdf)
    expected = load(name)

    assert cli.main([str(pdf)]) == 0

    detected = json.loads((tmp_path / f"{name}.gts.json").read_text())
    assert detected["source"] == expected["source"]
    got = [m["region"] for m in measures(detected)]
    want = [m["region"] for m in measures(expected)]
    assert [r["page"] for r in got] == [r["page"] for r in want]
    for g, w in zip(got, want):
        assert g["bbox"] == pytest.approx(w["bbox"], abs=0.003)


@pytest.mark.parametrize("name", SAMPLES)
def test_If_a_sample_is_engraved_and_scanned_measures_should_be_found_where_they_were_drawn(name):
    sample = SAMPLES[name]
    document = load(name)
    if not document["meta"]["title"].isascii() and find_japanese_font() is None:
        pytest.skip("no Japanese font to engrave this sample; set GTS_JP_FONT")
    pages, truth = engrave(document, sample.systems_per_page)

    for index, (page, (rotation, skew)) in enumerate(zip(pages, sample.scans, strict=True)):
        layout, _ = analyze_page(simulate_scan(page, rotation=rotation, skew=skew))

        assert layout.rotation == rotation
        spans = [span for system in layout.systems for span in measure_spans(system)]
        drawn = [t for t in truth if t.page == index]
        assert len(spans) == len(drawn)
        # Deskewing leaves at most a few pixels of error at 2122 px width.
        for (x0, x1), t in zip(spans, drawn):
            assert x0 == pytest.approx(t.x0, abs=12)
            assert x1 == pytest.approx(t.x1, abs=12)
