"""End-to-end checks on the public-domain sample score (Twinkle, Twinkle).

The sample is regenerated by tests/make_twinkle_sample.py; these tests keep
the committed PDF, the committed gts file and the detector consistent.
"""

import json
import shutil
from fractions import Fraction
from pathlib import Path

import jsonschema
import pytest

from engrave import engrave, simulate_scan
from layoutscan import cli
from layoutscan.detect import analyze_page, measure_spans
from layoutscan.render import sha256_of

REPO = Path(__file__).parents[3]
SCHEMA = json.loads((REPO / "schemas" / "gts.schema.json").read_text())
PDF = REPO / "schemas" / "examples" / "twinkle-twinkle.pdf"
GTS = REPO / "schemas" / "examples" / "twinkle-twinkle.gts.json"


@pytest.fixture(scope="module")
def sample():
    return json.loads(GTS.read_text())


def measures(document):
    return [m for section in document["sections"] for m in section["measures"]]


def duration(beat):
    d = beat["duration"]
    value = Fraction(1, d["value"]) * (Fraction(3, 2) if d.get("dots") else 1)
    if "tuplet" in d:
        value = value * d["tuplet"][1] / d["tuplet"][0]
    return value


def test_If_the_sample_is_loaded_it_should_be_a_valid_gts_with_all_layers(sample):
    jsonschema.validate(sample, SCHEMA)
    assert sample["meta"]["layers"] == ["layout", "structure", "chords", "tab"]
    assert [s["label"] for s in sample["sections"]] == ["A", "B", "A'"]
    assert all("region" in m and m.get("chords") and m.get("beats") for m in measures(sample))


def test_If_the_sample_tab_is_read_every_measure_should_fill_four_four(sample):
    for measure in measures(sample):
        assert sum(duration(b) for b in measure["beats"]) == 1, measure["id"]


def test_If_the_sample_pdf_is_committed_its_hash_should_match_the_gts_source(sample):
    assert sha256_of(PDF) == sample["source"]["sha256"]


def test_If_layoutscan_runs_on_the_sample_pdf_it_should_reproduce_the_layout_layer(sample, tmp_path):
    pdf = tmp_path / PDF.name
    shutil.copy(PDF, pdf)

    assert cli.main([str(pdf)]) == 0

    detected = json.loads((tmp_path / "twinkle-twinkle.gts.json").read_text())
    assert detected["source"] == sample["source"]
    got = [m["region"] for m in measures(detected)]
    expected = [m["region"] for m in measures(sample)]
    assert [r["page"] for r in got] == [r["page"] for r in expected]
    for g, e in zip(got, expected):
        assert g["bbox"] == pytest.approx(e["bbox"], abs=0.003)


def test_If_the_sample_is_engraved_and_scanned_measures_should_be_found_where_they_were_drawn(sample):
    pages, truth = engrave(sample)

    layout, _ = analyze_page(simulate_scan(pages[0], rotation=90, skew=0.4))

    assert layout.rotation == 90
    spans = [span for system in layout.systems for span in measure_spans(system)]
    assert len(spans) == len(truth) == 12
    # Deskewing leaves at most a few pixels of error at 2122 px width.
    for (x0, x1), drawn in zip(spans, truth):
        assert x0 == pytest.approx(drawn.x0, abs=12)
        assert x1 == pytest.approx(drawn.x1, abs=12)
